# -*- coding: utf-8 -*-
"""EDA_CropRecommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XtJim6fBgCtNbOTgYAzYjRJar9GD7O3k
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def EDA(data):
  df = pd.read_csv(data)

  print("Data Shape is:",df.shape)
  print("="*50)
  print("\n Column Info:")
  print(df.info())
  print("\nMissing Value:")
  print(df.isnull().sum())
  print("\nDuplicate Value:")
  print(df.duplicated().sum())
  print("\nClass Balance:")
  print(df["label"].value_counts())
  print("\nDescription of Data")
  print(df.describe())

  plt.figure(figsize=(10,5))
  df["label"].value_counts().plot(kind='bar')
  plt.title("Class Balance")
  plt.xlabel("Class")
  plt.ylabel("Count")
  plt.tight_layout()
  plt.show()

def NPKDistribution(data):
  df = pd.read_csv(data)
  fig, axes = plt.subplots(1, 3, figsize=(18, 5))
  for ax, col in zip(axes, ["N", "P", "K"]):
        sns.boxplot(data=df, x="label", y=col, ax=ax)
        ax.set_title(f"{col} by Crop")
        ax.tick_params(axis="x", rotation=45)
  plt.tight_layout()
  plt.show()

EDA("Crop_recommendation.csv")
NPKDistribution("Crop_recommendation.csv")