# -*- coding: utf-8 -*-
"""Train_Crop_Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZ5jyqdF4D8Ys5KhhSLYy_kbv7Kngulh
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import json
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

def load_data(data):
  df = pd.read_csv(data)
  x = df.drop('label',axis = 1)
  y = df['label']
  return x,y,df

def train_rf(x_train,y_trian):
  print("RandomForest GridSearch")
  param_grid = {
      'n_estimators': [100,200,300],
      'max_depth': [None,10,20],
      'min_samples_split': [2,5,10],
      'min_samples_leaf': [1,2,4]
  }
  rf = RandomForestClassifier(random_state=42)
  grid_search = GridSearchCV(estimator = rf,param_grid = param_grid,cv = 5,scoring="accuracy",n_jobs=-1,verbose=1)
  grid_search.fit(x_train,y_trian)
  best_params = grid_search.best_params_
  print("Best rf Parameters:",best_params)
  print("Best CV accuracy: {:.4f}".format(grid_search.best_score_))
  return grid_search.best_estimator_,grid_search.best_params_,grid_search.best_score_

def train_xgb(x_train,y_train_enc):
  print("XGBoost GridSearch")
  param_grid = {
      'n_estimators': [100,200],
      "learning_rate": [0.05, 0.1, 0.2],
      "max_depth": [3, 5, 7],
  }
  xgb = XGBClassifier(random_state=42,n_jobs = -1,eval_metric="mlogloss")
  grid_search = GridSearchCV(estimator = xgb,param_grid = param_grid,cv = 5,scoring="accuracy",n_jobs=-1,verbose=1)
  grid_search.fit(x_train,y_train_enc)
  best_params = grid_search.best_params_
  print("Best xgb Parameters:",best_params)
  print("Best CV accuracy: {:.4f}".format(grid_search.best_score_))
  return grid_search.best_estimator_,grid_search.best_params_,grid_search.best_score_

def evaluate(model,x_test,y_test,label_encoder=None,model_name = "model"):
  preds = model.predict(x_test)
  if label_encoder is not None:
    y_test_labels = pd.Series(label_encoder.inverse_transform(y_test))
    preds_labels = pd.Series(label_encoder.inverse_transform(preds))
  else:
    y_test_labels = pd.Series(y_test).reset_index(drop=True)
    preds_labels = pd.Series(preds)
  acc = accuracy_score(y_test_labels,preds_labels)
  class_report = classification_report(y_test_labels,preds_labels)
  print(f"\n{model_name} Test Accuracy: {acc:.4f}")
  print(f"\n{model_name} Classification Report:\n{class_report}")

  labels_sorted = sorted(y_test_labels.unique())
  cm = confusion_matrix(y_test_labels,preds_labels,labels=labels_sorted)
  plt.figure(figsize=(12,10))
  sns.heatmap(cm,annot=True,fmt="d",cmap="Blues",xticklabels=labels_sorted,yticklabels=labels_sorted)
  plt.title(f"{model_name} Confusion Matrix")
  plt.xlabel("Predicted Labels")
  plt.ylabel("True Labels")
  plt.xticks(rotation=90)
  plt.yticks(rotation=0)
  plt.tight_layout()
  plt.show()
  return acc,class_report

def main():
  x,y,df = load_data("Crop_recommendation.csv")
  x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42,stratify = y)
  results = {}
  rf_model,rf_params,rf_cv_score = train_rf(x_train,y_train)
  rf_acc,rf_report = evaluate(rf_model,x_test,y_test,model_name="RandomForest")
  joblib.dump(rf_model,"rf_model.pkl")
  results["RandomForest"] = {"best_params":rf_params,"cv_accuracy":rf_cv_score,"test_accuracy":rf_acc}
  print("Test Accuracy:",rf_acc)
  print("Train Accracy:",rf_model.score(x_train,y_train))
  l = LabelEncoder()
  y_train_enc = l.fit_transform(y_train)
  y_test_enc = l.transform(y_test)

  xgb_model,xgb_params,xgb_cv_score = train_xgb(x_train,y_train_enc)
  xgb_acc,xgb_report = evaluate(xgb_model,x_test,y_test_enc,label_encoder=l,model_name="XGBoost")
  joblib.dump(xgb_model,"xgb_model.pkl")
  joblib.dump(l,"label_encoder.pkl")
  results["XGBoost"] = {"best_params":xgb_params,"cv_accuracy":xgb_cv_score,"test_accuracy":xgb_acc}
  print("Test Accuracy:",xgb_acc)
  print("Train Accracy:",xgb_model.score(x_train,y_train_enc))
  print(results)

main()













