# -*- coding: utf-8 -*-
"""train_disease_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_heQkmMeM8G2eyYdBtdpiMw11cC4aWaf
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("emmarex/plantdisease")

print("Path to dataset files:", path)

import os
import json
import shutil
import random
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.applications import MobileNetV2, ResNet50
from tensorflow.keras.preprocessing.image import ImageDataGenerator

def find_class_root(base_path):
    for root, dirs, files in os.walk(base_path):
        if len(dirs) >= 10:
            image_exts = (".jpg", ".jpeg", ".png")
            sample_dir = os.path.join(root, dirs[0])
            if any(f.lower().endswith(image_exts) for f in os.listdir(sample_dir)):
                return root
    raise RuntimeError(f"Could not locate class folders under {base_path}")

CLASS_ROOT = find_class_root(path)
print("Found class folders at:", CLASS_ROOT)
print("Classes found:", os.listdir(CLASS_ROOT))

SPLIT_DIR = "/content/plantvillage_split"
TRAIN_DIR = os.path.join(SPLIT_DIR, "train")
VAL_DIR = os.path.join(SPLIT_DIR, "val")

def create_split(class_root, train_dir, val_dir, val_fraction=0.2, seed=42):
    if os.path.exists(SPLIT_DIR):
        print("Split already exists, skipping re-split.")
        return
    random.seed(seed)
    classes = [d for d in os.listdir(class_root) if os.path.isdir(os.path.join(class_root, d))]
    for cls in classes:
        src_dir = os.path.join(class_root, cls)
        images = [f for f in os.listdir(src_dir) if f.lower().endswith((".jpg", ".jpeg", ".png"))]
        random.shuffle(images)
        n_val = max(1, int(len(images) * val_fraction))
        val_images = images[:n_val]
        train_images = images[n_val:]

        os.makedirs(os.path.join(train_dir, cls), exist_ok=True)
        os.makedirs(os.path.join(val_dir, cls), exist_ok=True)

        for img in train_images:
            shutil.copy(os.path.join(src_dir, img), os.path.join(train_dir, cls, img))
        for img in val_images:
            shutil.copy(os.path.join(src_dir, img), os.path.join(val_dir, cls, img))

        print(f"{cls}: {len(train_images)} train, {len(val_images)} val")

print("\nCreating train/val split...")
create_split(CLASS_ROOT, TRAIN_DIR, VAL_DIR)

"""***Not Finished***"""





