# -*- coding: utf-8 -*-
"""train_disease_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hd3B9iL0EvH2C85bzgUM587dE7euAbmu
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("emmarex/plantdisease")

print("Path to dataset files:", path)

import os
import json
import shutil
import random
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.applications import MobileNetV2, ResNet50
from tensorflow.keras.preprocessing.image import ImageDataGenerator

def find_class_root(base_path):
    for root, dirs, files in os.walk(base_path):
        if len(dirs) >= 10:
            image_exts = (".jpg", ".jpeg", ".png")
            sample_dir = os.path.join(root, dirs[0])
            if any(f.lower().endswith(image_exts) for f in os.listdir(sample_dir)):
                return root
    raise RuntimeError(f"Could not locate class folders under {base_path}")

CLASS_ROOT = find_class_root(path)
print("Found class folders at:", CLASS_ROOT)
print("Classes found:", os.listdir(CLASS_ROOT))

SPLIT_DIR = "/content/plantvillage_split"
TRAIN_DIR = os.path.join(SPLIT_DIR, "train")
VAL_DIR = os.path.join(SPLIT_DIR, "val")

def create_split(class_root, train_dir, val_dir, val_fraction=0.2, seed=42):
    if os.path.exists(SPLIT_DIR):
        print("Split already exists, skipping re-split.")
        return
    random.seed(seed)
    classes = [d for d in os.listdir(class_root) if os.path.isdir(os.path.join(class_root, d))]
    for cls in classes:
        src_dir = os.path.join(class_root, cls)
        images = [f for f in os.listdir(src_dir) if f.lower().endswith((".jpg", ".jpeg", ".png"))]
        random.shuffle(images)
        n_val = max(1, int(len(images) * val_fraction))
        val_images = images[:n_val]
        train_images = images[n_val:]

        os.makedirs(os.path.join(train_dir, cls), exist_ok=True)
        os.makedirs(os.path.join(val_dir, cls), exist_ok=True)

        for img in train_images:
            shutil.copy(os.path.join(src_dir, img), os.path.join(train_dir, cls, img))
        for img in val_images:
            shutil.copy(os.path.join(src_dir, img), os.path.join(val_dir, cls, img))

        print(f"{cls}: {len(train_images)} train, {len(val_images)} val")

print("\nCreating train/val split...")
create_split(CLASS_ROOT, TRAIN_DIR, VAL_DIR)

MODEL_NAME = "mobilenet_v2"
MODEL_DIR = "/content/models"
OUT_DIR = "/content/outputs"

def get_generators():
  train_datagen = ImageDataGenerator(
      rescale=1.0/255,
      rotation_range=15,
      horizontal_flip=True,
      brightness_range=(0.8, 1.2),
      zoom_range=0.1
  )
  val_datagen = ImageDataGenerator(rescale=1.0/255)
  train_gen = train_datagen.flow_from_directory(
      TRAIN_DIR,
      target_size=(224, 224),
      batch_size=32,
      class_mode='categorical',
      shuffle=True
  )
  val_gen = val_datagen.flow_from_directory(
      VAL_DIR,
      target_size=(224, 224),
      batch_size=32,
      class_mode='categorical',
      shuffle=False
  )
  return train_gen, val_gen

def build_model(model_name,num_classes):
  input_shape = (224,224,3)

  if model_name == "MobileNetV2":
    base_model = MobileNetV2(input_shape=input_shape, include_top=False, weights="imagenet")
  else:
    raise ValueError(f"Unknown model name: {model_name}")
  base_model.trainable = False
  model = models.Sequential([
      base_model,
      layers.GlobalAveragePooling2D(),
      layers.Dropout(0.5),
      layers.Dense(num_classes, activation="softmax")
  ])
  model.compile(
      optimizer = optimizers.Adam(learning_rate=0.001),
      loss="categorical_crossentropy",
      metrics=["accuracy"]
  )
  return model,base_model

def plot_history(history,out_path,phase2_history=None):
  acc = history.history["accuracy"]
  val_acc = history.history["val_accuracy"]
  loss = history.history["loss"]
  val_loss = history.history["val_loss"]
  if phase2_history is not None:
    acc += phase2_history.history["accuracy"]
    val_acc += phase2_history.history["val_accuracy"]
    loss += phase2_history.history["loss"]
    val_loss += phase2_history.history["val_loss"]
  fig,axes = plt.subplots(1,2,figsize=(12,4))
  axes[0].plot(loss,label="Training Accuracy")
  axes[0].plot(val_loss,label="Validation Accuracy")
  axes[0].set_title("Loss")
  axes[0].set_xlabel("Epochs")
  axes[0].legend()

  axes[1].plot(acc, label="train")
  axes[1].plot(val_acc, label="val")
  axes[1].set_title("Accuracy")
  axes[1].set_xlabel("Epoch")
  axes[1].legend()

  plt.tight_layout()
  plt.savefig(out_path)
  plt.show()

train_gen, val_gen = get_generators()
class_indices = train_gen.class_indices
classes = sorted(class_indices,key=class_indices.get)
print(f"\nClasses ({len(classes)}) : {classes}")
print(f"Train samples: {train_gen.samples} | Val samples: {val_gen.samples}")
model,base_model = build_model("MobileNetV2",len(classes))
model.summary()

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(OUT_DIR, exist_ok=True)

print(f"\nPhase 1: Training Now... {10} Epochs")
history = model.fit(train_gen,epochs=10,validation_data=val_gen)
best_val_acc = max(history.history["val_accuracy"])
print(f"\nBest val accuracy (phase 1): {best_val_acc:.4f}")
model.save(f"{MODEL_DIR}/disease_detection_{MODEL_NAME}_phase1.keras")
with open(f"{MODEL_DIR}/disease_detection_classes.json", "w") as f:
    json.dump(classes, f, indent=2)
print(f"\nPhase 2: fine-tuning full network ({5} epochs)...")
base_model.trainable = True
model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-5),
    loss="categorical_crossentropy",
    metrics=["accuracy"],
)
history2 = model.fit(
    train_gen,
    epochs=5,
    validation_data=val_gen,
)
best_val_acc2 = max(history2.history["val_accuracy"])
print(f"\nBest val accuracy (phase 2, fine-tuned): {best_val_acc2:.4f}")
model.save(f"{MODEL_DIR}/disease_detection_{MODEL_NAME}_finetuned.keras")

plot_history(history, f"{OUT_DIR}/disease_detection_training_curves.png", phase2_history=history2)
with open(f"{OUT_DIR}/disease_detection_history.json", "w") as f:
    json.dump({
        "phase1_val_acc": history.history["val_accuracy"],
        "phase2_val_acc": history2.history["val_accuracy"],
        "best_val_acc": max(best_val_acc, best_val_acc2),
        "model_name": MODEL_NAME,
    }, f, indent=2)

print(f"\nFinal best val accuracy: {max(best_val_acc, best_val_acc2):.4f}")
print(f"Model saved to {MODEL_DIR}/disease_detection_{MODEL_NAME}_finetuned.keras")





