# -*- coding: utf-8 -*-
"""train_disease_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_heQkmMeM8G2eyYdBtdpiMw11cC4aWaf
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("emmarex/plantdisease")

print("Path to dataset files:", path)

import os
import json
import shutil
import random
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.applications import MobileNetV2, ResNet50
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
def find_class_root(base_path):
    for root, dirs, files in os.walk(base_path):
        if len(dirs) >= 10:
            image_exts = (".jpg", ".jpeg", ".png")
            sample_dir = os.path.join(root, dirs[0])
            if any(f.lower().endswith(image_exts) for f in os.listdir(sample_dir)):
                return root
    raise RuntimeError(f"Could not locate class folders under {base_path}")

CLASS_ROOT = find_class_root(path)
print("Found class folders at:", CLASS_ROOT)
print("Classes found:", os.listdir(CLASS_ROOT))

# ============ 2. Split into train/val (80/20) ============
SPLIT_DIR = "/content/plantvillage_split"
TRAIN_DIR = os.path.join(SPLIT_DIR, "train")
VAL_DIR = os.path.join(SPLIT_DIR, "val")

def create_split(class_root, train_dir, val_dir, val_fraction=0.2, seed=42):
    if os.path.exists(SPLIT_DIR):
        print("Split already exists, skipping re-split.")
        return
    random.seed(seed)
    classes = [d for d in os.listdir(class_root) if os.path.isdir(os.path.join(class_root, d))]
    class_counts = {}
    for cls in classes:
        src_dir = os.path.join(class_root, cls)
        images = [f for f in os.listdir(src_dir) if f.lower().endswith((".jpg", ".jpeg", ".png"))]
        random.shuffle(images)
        n_val = max(1, int(len(images) * val_fraction))
        val_images = images[:n_val]
        train_images = images[n_val:]
        class_counts[cls] = {"train": len(train_images), "val": len(val_images)}

        os.makedirs(os.path.join(train_dir, cls), exist_ok=True)
        os.makedirs(os.path.join(val_dir, cls), exist_ok=True)
        for img in train_images:
            shutil.copy(os.path.join(src_dir, img), os.path.join(train_dir, cls, img))
        for img in val_images:
            shutil.copy(os.path.join(src_dir, img), os.path.join(val_dir, cls, img))

    print("\nClass distribution (train/val):")
    for cls, counts in sorted(class_counts.items(), key=lambda x: x[1]["train"]):
        print(f"  {cls}: {counts['train']} train, {counts['val']} val")

    max_count = max(c["train"] for c in class_counts.values())
    min_count = min(c["train"] for c in class_counts.values())
    print(f"\nImbalance ratio (largest/smallest class): {max_count / min_count:.1f}x")

print("\nCreating train/val split...")
create_split(CLASS_ROOT, TRAIN_DIR, VAL_DIR)

# ============ 3. Config ============
MODEL_NAME = "mobilenet_v2"   # matches build_model's "mobilenet_v2" branch below
IMG_SIZE = 224
BATCH_SIZE = 32
PHASE1_EPOCHS = 10
PHASE2_EPOCHS = 5
MODEL_DIR = "/content/models"
OUT_DIR = "/content/outputs"
os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(OUT_DIR, exist_ok=True)

print(f"\nGPU available: {tf.config.list_physical_devices('GPU')}")

# ============ 4. Data generators ============
def get_generators():
    train_datagen = ImageDataGenerator(
        rescale=1.0 / 255,
        rotation_range=15,
        horizontal_flip=True,
        brightness_range=(0.8, 1.2),
        zoom_range=0.1,
    )
    val_datagen = ImageDataGenerator(rescale=1.0 / 255)

    train_gen = train_datagen.flow_from_directory(
        TRAIN_DIR, target_size=(IMG_SIZE, IMG_SIZE),
        batch_size=BATCH_SIZE, class_mode="categorical", shuffle=True,
    )
    # shuffle=False here is important -- we need predictions to line up with
    # true labels in order for sklearn's classification_report
    val_gen = val_datagen.flow_from_directory(
        VAL_DIR, target_size=(IMG_SIZE, IMG_SIZE),
        batch_size=BATCH_SIZE, class_mode="categorical", shuffle=False,
    )
    return train_gen, val_gen

# ============ 5. Model ============
def build_model(model_name, num_classes):
    input_shape = (IMG_SIZE, IMG_SIZE, 3)
    if model_name == "mobilenet_v2":
        base_model = MobileNetV2(input_shape=input_shape, include_top=False, weights="imagenet")
    elif model_name == "resnet50":
        base_model = ResNet50(input_shape=input_shape, include_top=False, weights="imagenet")
    else:
        raise ValueError(f"Unknown model name: {model_name}")

    base_model.trainable = False
    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation="softmax"),
    ])
    model.compile(
        optimizer=optimizers.Adam(learning_rate=0.001),
        loss="categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model, base_model

# ============ 6. Class weights (handles imbalance) ============
def get_class_weights(train_gen):
    labels = train_gen.classes  # integer labels for every training sample
    classes_arr = np.unique(labels)
    weights = compute_class_weight(class_weight="balanced", classes=classes_arr, y=labels)
    return dict(zip(classes_arr.tolist(), weights.tolist()))

# ============ 7. Per-class evaluation ============
def evaluate_per_class(model, val_gen, classes):
    val_gen.reset()
    preds = model.predict(val_gen, verbose=0)
    pred_labels = np.argmax(preds, axis=1)
    true_labels = val_gen.classes[: len(pred_labels)]

    report = classification_report(
        true_labels, pred_labels, target_names=classes, output_dict=True, zero_division=0
    )
    return report, true_labels, pred_labels

def print_per_class_report(report, classes):
    print("\nPer-class precision/recall/F1:")
    print(f"{'Class':45s} {'Precision':>10s} {'Recall':>10s} {'F1':>10s}")
    for cls in classes:
        r = report[cls]
        print(f"{cls:45s} {r['precision']:10.3f} {r['recall']:10.3f} {r['f1-score']:10.3f}")
    print(f"\n{'Macro avg':45s} {report['macro avg']['precision']:10.3f} "
          f"{report['macro avg']['recall']:10.3f} {report['macro avg']['f1-score']:10.3f}")

    weak_classes = [cls for cls in classes if report[cls]["recall"] < 0.85]
    if weak_classes:
        print(f"\n⚠ Classes with recall < 0.85 (higher risk of missed diagnosis):")
        for cls in weak_classes:
            print(f"  - {cls}: recall = {report[cls]['recall']:.3f}")
    else:
        print("\n✓ All classes have recall >= 0.85")

def plot_confusion_matrix(true_labels, pred_labels, classes, out_path):
    cm = confusion_matrix(true_labels, pred_labels, labels=list(range(len(classes))))
    plt.figure(figsize=(12, 10))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=classes, yticklabels=classes)
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.xticks(rotation=90)
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig(out_path)
    plt.show()

def plot_history(history, out_path, phase2_history=None):
    acc = history.history["accuracy"]
    val_acc = history.history["val_accuracy"]
    loss = history.history["loss"]
    val_loss = history.history["val_loss"]
    if phase2_history is not None:
        acc += phase2_history.history["accuracy"]
        val_acc += phase2_history.history["val_accuracy"]
        loss += phase2_history.history["loss"]
        val_loss += phase2_history.history["val_loss"]

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    axes[0].plot(loss, label="train")
    axes[0].plot(val_loss, label="val")
    axes[0].set_title("Loss")
    axes[0].set_xlabel("Epoch")
    axes[0].legend()

    axes[1].plot(acc, label="train")
    axes[1].plot(val_acc, label="val")
    axes[1].set_title("Accuracy")
    axes[1].set_xlabel("Epoch")
    axes[1].legend()

    plt.tight_layout()
    plt.savefig(out_path)
    plt.show()

# ============ 8. Run ============
train_gen, val_gen = get_generators()
class_indices = train_gen.class_indices
classes = sorted(class_indices, key=class_indices.get)
print(f"\nClasses ({len(classes)}): {classes}")
print(f"Train samples: {train_gen.samples} | Val samples: {val_gen.samples}")

class_weights = get_class_weights(train_gen)
print("\nClass weights (higher = rarer class, weighted more in loss):")
for idx, w in class_weights.items():
    print(f"  {classes[idx]}: {w:.3f}")

model, base_model = build_model(MODEL_NAME, len(classes))
model.summary()

# ---------- Phase 1: train head only ----------
print(f"\nPhase 1: training head only ({PHASE1_EPOCHS} epochs)...")
history = model.fit(
    train_gen,
    epochs=PHASE1_EPOCHS,
    validation_data=val_gen,
    class_weight=class_weights,
)
best_val_acc = max(history.history["val_accuracy"])
print(f"\nBest val accuracy (phase 1): {best_val_acc:.4f}")

report1, true1, pred1 = evaluate_per_class(model, val_gen, classes)
print_per_class_report(report1, classes)
phase1_macro_recall = report1["macro avg"]["recall"]

model.save(f"{MODEL_DIR}/disease_detection_{MODEL_NAME}_phase1.keras")
with open(f"{MODEL_DIR}/disease_detection_classes.json", "w") as f:
    json.dump(classes, f, indent=2)

# ---------- Phase 2: fine-tune full network ----------
print(f"\nPhase 2: fine-tuning full network ({PHASE2_EPOCHS} epochs)...")
base_model.trainable = True
model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-5),
    loss="categorical_crossentropy",
    metrics=["accuracy"],
)
history2 = model.fit(
    train_gen,
    epochs=PHASE2_EPOCHS,
    validation_data=val_gen,
    class_weight=class_weights,
)
best_val_acc2 = max(history2.history["val_accuracy"])
print(f"\nBest val accuracy (phase 2, fine-tuned): {best_val_acc2:.4f}")

report2, true2, pred2 = evaluate_per_class(model, val_gen, classes)
print_per_class_report(report2, classes)
phase2_macro_recall = report2["macro avg"]["recall"]

# ---------- Select the better phase by macro RECALL, not accuracy ----------
# A missed disease (false negative) matters more here than a false alarm,
# so the "best" checkpoint is whichever phase caught diseases more reliably
# across classes, not just whichever had higher raw accuracy.
if phase2_macro_recall >= phase1_macro_recall:
    print(f"\nPhase 2 wins on macro recall ({phase2_macro_recall:.4f} >= {phase1_macro_recall:.4f}) -- using fine-tuned model as best.")
    best_report, best_true, best_pred = report2, true2, pred2
    model.save(f"{MODEL_DIR}/disease_detection_{MODEL_NAME}_best.keras")
else:
    print(f"\nPhase 1 wins on macro recall ({phase1_macro_recall:.4f} > {phase2_macro_recall:.4f}) -- fine-tuning hurt recall, reverting.")
    # reload phase 1 weights since `model` object now holds phase 2 (fine-tuned) weights
    model = tf.keras.models.load_model(f"{MODEL_DIR}/disease_detection_{MODEL_NAME}_phase1.keras")
    best_report, best_true, best_pred = report1, true1, pred1
    model.save(f"{MODEL_DIR}/disease_detection_{MODEL_NAME}_best.keras")

plot_history(history, f"{OUT_DIR}/disease_detection_training_curves.png", phase2_history=history2)
plot_confusion_matrix(best_true, best_pred, classes, f"{OUT_DIR}/disease_detection_confusion_matrix.png")

with open(f"{MODEL_DIR}/disease_detection_config.json", "w") as f:
    json.dump({"model_name": MODEL_NAME, "img_size": IMG_SIZE}, f, indent=2)

with open(f"{OUT_DIR}/disease_detection_history.json", "w") as f:
    json.dump({
        "phase1_val_acc": history.history["val_accuracy"],
        "phase2_val_acc": history2.history["val_accuracy"],
        "phase1_macro_recall": phase1_macro_recall,
        "phase2_macro_recall": phase2_macro_recall,
        "best_macro_recall": max(phase1_macro_recall, phase2_macro_recall),
        "per_class_report": best_report,
        "model_name": MODEL_NAME,
    }, f, indent=2)

print(f"\nFinal best macro recall: {max(phase1_macro_recall, phase2_macro_recall):.4f}")
print(f"Best model saved to {MODEL_DIR}/disease_detection_{MODEL_NAME}_best.keras")